### ISSUE TITLE
new npm package ?

### ISSUE THREAD

**Issue by matthiasg** [ramv/node-elastical#15]
The version on npm is quite outdated compared to master .. any chance to push the next version or is master deemed unstable ? I was specifically looking for aliases which have been added just AFTER the current version was published ... they at least look stable to me...

BTW: good library so far!

**Comment by ramv** [comment]
hey Mathais, thanks for the kind words. I will push a new release tomorrow.

**Comment by ramv** [comment]
Done. Sorry for the delay. The tests were broken after a pull so had to put some hours in to make it cleaner.

**Comment by draco2003** [comment]
+1 for new npm version (with the river fix)

**Comment by ramv** [comment]
Hi,
Will get one out today. Apologies for the delay.

On Monday, December 30, 2013, Dan Rowe wrote:

> +1 for new npm version (with the river fix)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ramv/node-elastical/issues/15#issuecomment-31381654
> .

## 

Best Regards,

Ram Viswanadha

**Comment by ramv** [comment]
pushed new version.
