### ISSUE TITLE
putRiver does not work because wrapper function mistreats its arguments

### ISSUE THREAD

**Issue by mauritslamers** [ramv/node-elastical#18]
When trying to use Client#putRiver with the latest npm module (0.0.12), the command fails without error message. 

The reason why it fails is that the Client.putRiver method is created by the wrapIndexMethod function (https://github.com/ramv/node-elastical/blob/master/lib/client.js#L1052) which removes the first argument from the given function. 

This results in Index.putRiver called without the name parameter, because it is sliced off by the wrapIndexMethod implementation.

The arguments to putRiver are (name, config, callback), which when called becomes Index#putRiver(client, config, callback) instead of the intended Index#putRiver(client, name, config, callback).

**Comment by ramv** [comment]
thanks for the bug report. will fix it ASAP

On Mon, Dec 2, 2013 at 4:40 AM, Maurits Lamers notifications@github.comwrote:

> When trying to use Client#putRiver with the latest npm module (0.0.12),
> the command fails without error message.
> 
> The reason why it fails is that the Client.putRiver method is created by
> the wrapIndexMethod function (
> https://github.com/ramv/node-elastical/blob/master/lib/client.js#L1052)
> which removes the first argument from the given function.
> 
> This results in Index.putRiver called without the name parameter, because
> it is sliced off by the wrapIndexMethod implementation.
> 
> The arguments to putRiver are (name, config, callback), which when called
> becomes Index#putRiver(client, config, callback) instead of the intended
> Index#putRiver(client, name, config, callback).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ramv/node-elastical/issues/18
> .

## 

Best Regards,

Ram Viswanadha
