### ISSUE TITLE
Put docs on Github pages

### ISSUE THREAD

**Issue by KyleAMathews** [ramv/node-elastical#22]
It's really great that you have extensive docs... except it's impossible to read them unless I clone the repo and run them locally. Which I generally don't want to in the heat of working on a small change to my ES code. Just putting them on Github pages and linking to them from the README would make them much more accessible.

**Comment by ramv** [comment]
The docs are accessible via http://ramv.github.io/node-elastical/docs/

On Fri, Jan 17, 2014 at 9:47 AM, Kyle Mathews notifications@github.comwrote:

> It's really great that you have extensive docs... except it's impossible
> to read them unless I clone the repo and run them locally. Which I
> generally don't want to in the heat of working on a small change to my ES
> code. Just putting them on Github pages and linking to them from the README
> would make them much more accessible.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ramv/node-elastical/issues/22
> .

## 

Best Regards,

Ram Viswanadha

**Comment by ramv** [comment]
I will link them from the readme

On Fri, Jan 17, 2014 at 10:55 AM, Ram Viswanadha rviswanadha@gmail.comwrote:

> The docs are accessible via http://ramv.github.io/node-elastical/docs/
> 
> On Fri, Jan 17, 2014 at 9:47 AM, Kyle Mathews notifications@github.comwrote:
> 
> > It's really great that you have extensive docs... except it's impossible
> > to read them unless I clone the repo and run them locally. Which I
> > generally don't want to in the heat of working on a small change to my ES
> > code. Just putting them on Github pages and linking to them from the README
> > would make them much more accessible.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/ramv/node-elastical/issues/22
> > .
> 
> ## 
> 
> Best Regards,
> 
> Ram Viswanadha

## 

Best Regards,

Ram Viswanadha
