### ISSUE TITLE
TTL

### ISSUE THREAD

**Issue by tj** [ramv/node-elastical#24]
any way of specifying the TTL through this api?

**Comment by ramv** [comment]
Are you referring to connection timeout? if so, yes.

**Comment by ramv** [comment]
``` javascript
var client = new elastical.Client('example.com', {port: 1234, timeout:50 /*time in milli seconds*/});
```

should set the `timeout`.

**Comment by tj** [comment]
sorry for the individual doc

**Comment by ramv** [comment]
no worries. I am thrilled that you are using Elastical !

**Comment by tj** [comment]
:D you can pass in `_ttl` some how right? bit of an ES noob but it seemed like you can set the ttl field per doc, might be something nice to add to this lib

**Comment by ramv** [comment]
oh .. you mean the `_ttl` for ElasticSearch documents that is referenced [here](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-ttl-field.html). Got it.
You need to use the `putMapping` API. See http://ramv.github.io/node-elastical/docs/classes/Client.html for more info

``` javascript
client.putMapping('tweets', 'tweet',  {  
                                 'tweet': { 
                                    "_ttl" : { "enabled" : true, "default": "1d" },
                                    'properties': { 
                                         'message': { 
                                              'type': 'string', 
                                              'store': 'yes' 
                                          }
                                     }
                                 }
                           });
```

**Comment by mallocator** [comment]
Actually there is a per document option for the TTL:
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-index_.html#index-ttl

Which I would also be interested in having :)

**Comment by ramv** [comment]
Sorry thats not the one you are looking for. Let me see if I can add it.

**Comment by mallocator** [comment]
No actually what you're referring to is one default TTL for all documents of a type. What I'm referencing is a per document TTL, which is also why I'm linking to a different part of the docs. ;)

**Comment by ericthelast** [comment]
FYI (for anyone landing here from search), the `index(type, doc, options, callback)` method does support specifying the [per-document ttl](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-index_.html#index-ttl) by setting the `ttl` property of `options` (https://github.com/ramv/node-elastical/blob/master/lib/index.js#L1067).
